dist: bionic
sudo: required

services: 
  - docker
before_install:
  - docker pull velocitymob/pandocker:buster
  - docker run --name buildvm -it -w /pandoc velocitymob/pandocker:buster  xelatex CurriculumVitae.tex
  - docker cp buildvm:/pandoc/CurriculumVitae.pdf cv.pdf
  - docker container rm -f buildvm
  

jobs:
  include:
  - stage: run docker
    script:
    - ls -la