name: Build LaTeX document
on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: package dockerwith
      run: |
        VERSION=(date +%s)
         docker login docker.pkg.github.com --username gpmontt --password ${{ secrets.GITHUB_TOKEN }}
         docker pull docker.pkg.github.com/gpmontt/githublebenslauf/pandocker_test:buster
         docker run --rm -i -v $(pwd):/pandoc  -w /pandoc -c "xelatex Anschreiben.tex & ls /pandoc"
         
        

