name: Build LaTeX document
on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile basic LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: Anschreiben.tex

