# This is a basic workflow to help you get started with Actions

name: builddocker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    - name: check out repository
      uses: actions/checkout@v2
    - name: Use local my action
      uses: ./.github/actions/testactions

#     # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
          echo Hello, world!
          ls -la
#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
