name: workflows

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Those steps are executed directly on the VM
    - run: echo $PWD

  container:
    runs-on: ubuntu-latest
    container: docker://velocitymob/pandocker:buster
    steps:
      - uses: actions/checkout@v2 
      - run: |
          printenv
          ls -la / 
          cd /__w/githublebenslauf/githublebenslauf
          ls -la
          xelatex --version        
          ls -al $HOME
        name: Run in container

    
