name: workflows

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Those steps are executed directly on the VM
    - run: echo $PWD

  container:
    runs-on: ubuntu-latest
    container: docker://velocitymob/pandocker:buster
    steps:
      - uses: actions/checkout@v2 
      - run: |
          printenv
          ls -la / 
          cd $GITHUB_WORKSPACE
          ls -la
          xelatex --version
          xelatex -interaction nonstopmode -halt-on-error -file-line-error Anschreiben.tex
          ls -la
          xelatex -interaction nonstopmode -halt-on-error -file-line-error CurriculumVitae.tex
        name: Run in container

  Release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Changelog
        run: |
         echo "# Good things have arrived" > ${{ github.workflow }}-CHANGELOG.txt
         echo ${{ secrets.MYVALUE }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workflow }}-CHANGELOG.txt
          files: Anschreibe.pdf
        env:
          DEPLOYTOKEN: ${{ secrets.DEPLOYTOKEN }}
          MYVALUE: ${{ secrets.MYVALUE }}   