name: workflows

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Those steps are executed directly on the VM
    - run: echo $PWD

  container:
    runs-on: ubuntu-latest
    container: docker://velocitymob/pandocker:buster
    steps:
      - uses: actions/checkout@v2 
      - run: |
          printenv
          ls -la / 
          cd $GITHUB_WORKSPACE
          ls -la
          xelatex --version
          xelatex -interaction nonstopmode -halt-on-error -file-line-error Anschreiben.tex
          ls -la
        name: Run in container

    
